pr:
  autoCancel: true
  
jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: |
      conda config --set always_yes yes --set changeps1 no
      conda info -a
      conda install --yes -c conda-forge -c bioconda python=$TRAVIS_PYTHON_VERSION --file requirements.txt
      conda install --yes -c conda-forge -c bioconda pytest flake8
      conda install --yes -c conda-forge -c bioconda nose
      conda install --yes pathlib
      conda install --yes -c defaults -c conda-forge -c bioconda configparser
      python setup.py install
      displayName: 'installing dependencies'
  - script: |
      py.test schicexplorer/test
      displayName: 'pytest'
  - script: |
      flake8 . --exclude=.venv,.build,planemo_test_env,build --ignore=E501,F401,F403,E402,F999,F405,E712,W504
      displayName: 'linting'
